stag_node:
  ros__parameters:
    # STag parameters
    libraryHD: 15
    errorCorrection: 7
    # Camera configuration
    camera_info_topic: /camera/color/camera_info
    raw_image_topic: /camera/color/image_raw
    is_compressed: false
    # Node configuration
    tag_tf_prefix: STag_
    show_markers: true
    publish_tf: true
