stag_node:
  ros__parameters:
    tags: "[]"
    bundles:
      "[
        {
          frame: 'bundle_4',
          tags: [
            {
              id: 76,
              corners: [
                [-0.0245 ,  0.0245, 0.0 ],
                [0.0245, 0.0245, 0.0 ],
                [0.0245,  -0.0245,  0.0 ]
              ]
            },
            {
              id: 92,
              corners: [
                [0.031,-0.0245, -0.0065 ],
                [0.031, 0.0245, -0.0065 ],
                [ 0.031, 0.0245,-0.0555 ]
              ]
            },
            {
              id: 103,
              corners: [
                [ -0.0245 ,   -0.031, -0.0065 ],
                [0.0245,   -0.031, -0.0065 ],
                [0.0245,   -0.031,-0.0555 ]
              ]
            },
            {
              id: 196,
              corners: [
                [ -0.041 ,   0.0245, -0.0065 ],
                [-0.041,   -0.0245, -0.0065 ],
                [-0.041,   -0.0245,-0.0555 ]
              ]
            }
          ]
        }
      ]"

# Marker corner order:
# 1          2
#  HD########
#  #ID#  ####
#  ##  ##  ##
#  ####  ####
#  ##########
# 4          3
