stag_node:
  ros__parameters:
    tags:
      "[
        {
          frame: 'tag_170',
          id: 170,
          corners: [
                [-0.0245 ,  0.0245, 0.0 ],
                [0.0245, 0.0245, 0.0 ],
                [0.0245,  -0.0245,  0.0 ]
              ]
        }
      ]"
    bundles: "[]"

# Marker corner order:
# 1          2
#  HD########
#  #ID#  ####
#  ##  ##  ##
#  ####  ####
#  ##########
# 4          3
