zme_fusion_map_node:
  ros__parameters:
    esdf_mode:  true
    scan_to_baselink_transform:
      px: 0.195
      py: 0.0
      pz: 0.0227
      roll: 0.0
      pitch: 0.0
      yaw: 1.56
    tof_to_baselink_transform:
      px: 0.22
      py: 0.0
      pz: 0.0727
      roll: 1.56
      pitch: 0.007
      yaw: 1.58
    realsense_to_baselink_transform:
      px: 0.12
      py: 0.0
      pz: 1.5
      roll: 0.994837
      pitch: -3.1416
      yaw: 1.580796
    resolution: 0.1
    update_esdf_every_n_sec:  0.1
    reserved_size:  1000000
    lx: -20.0
    ly: -20.0
    lz: -1.6
    rx: 20.0
    ry: 20.0
    rz: 2.0
    min_ray_length: 0.5
    max_ray_length: 5.0
    ray_cast_num_thread: 0
    center_x: 3.2247735741936430e+02
    center_y: 2.3707634648111778e+02
    focal_x:  3.8445808939187248e+02
    focal_y:  3.8398275569654390e+02
    p_hit:  0.7
    p_miss: 0.35
    p_min:  0.12
    p_max:  0.97
    p_occ:  0.8
    global_map: false
    global_update:  false
    global_vis: false
    radius_x: 10.0
    radius_y: 10.0
    radius_z: 1.5
    use_depth_filter: true
    depth_filter_tolerance: 0.1
    depth_filter_max_dist:  10.0
    depth_filter_min_dist:  0.1

    depth_filter_margin:  0
    visualize_every_n_updates:  10
    slice_vis_max_dist: 2.0

    slice_vis_level:  1.6

    vis_lower_bound:  0.0
    vis_upper_bound:  10.0

       